version: 1.0.{build}
branches:
  only:
  - master
  - /^v\d+(?:\.\d+)?$/
  - /[\b_]validate\b/
skip_tags: true
nuget:
  disable_publish_on_pr: true
image: Visual Studio 2015
configuration: Release
environment:
  VisualStudioVersion: 14.0
cache:
#- '%USERPROFILE%\.nuget\packages -> **\project.json'
- 'obj\tools -> tools\**'
before_build:
- ps: .\init.ps1
build:
  project: src\Microsoft.VisualStudio.Threading.sln
  parallel: true
  verbosity: minimal
test_script:
- cmd: >-
    "%userprofile%\.nuget\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe" 
    -register:user
    -target:"%xunit20%\xunit.console.x86.exe"
    -targetargs:"bin\Release\Profile111\Microsoft.VisualStudio.Threading.Tests.Portable.dll bin\Release\Microsoft.VisualStudio.Threading.Tests.Desktop.dll bin\Release\Microsoft.VisualStudio.Threading.Analyzers.Tests.dll -noshadow -html bin\release\testresults.html -xml bin\release\testresults.xml -appveyor -notrait TestCategory=FailsInCloudTest -nologo"
    -returntargetcode
    -excludebyattribute:*.ExcludeFromCodeCoverage*
    -excludebyfile:*\*Designer.cs
    -filter:"+[Microsoft.VisualStudio.Threading]* +[Microsoft.VisualStudio.Threading.Analyzers]*"
    -hideskipped:All
    -output:bin\Release\Threading_coverage.xml

    SET PATH=C:\Python34;C:\Python34\Scripts;%PATH%

    pip install codecov

    codecov -f "bin\Release\Threading_coverage.xml"
artifacts:
- path: bin\**\*.nupkg
  name: NuGet Package
