// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;

namespace Microsoft.VisualStudio.Threading.Analyzers;

internal static class CSharpCommonInterest
{
    internal static readonly IImmutableSet<SyntaxKind> MethodSyntaxKinds = ImmutableHashSet.Create(
        SyntaxKind.ConstructorDeclaration,
        SyntaxKind.MethodDeclaration,
        SyntaxKind.OperatorDeclaration,
        SyntaxKind.AnonymousMethodExpression,
        SyntaxKind.SimpleLambdaExpression,
        SyntaxKind.ParenthesizedLambdaExpression,
        SyntaxKind.GetAccessorDeclaration,
        SyntaxKind.SetAccessorDeclaration,
        SyntaxKind.AddAccessorDeclaration,
        SyntaxKind.RemoveAccessorDeclaration);

    /// <summary>
    /// Gets a symbol and any ref locals that alias it within the containing function.
    /// </summary>
    internal static ImmutableHashSet<ISymbol> GetSymbolAndRefAliases(SyntaxNodeAnalysisContext context, SyntaxNode node, ISymbol symbol)
    {
        ImmutableHashSet<ISymbol>.Builder symbols = ImmutableHashSet.CreateBuilder<ISymbol>(SymbolEqualityComparer.Default);
        symbols.Add(symbol);

        SyntaxNode searchRoot = node.AncestorsAndSelf().FirstOrDefault(
            ancestor => ancestor is AnonymousFunctionExpressionSyntax
                or LocalFunctionStatementSyntax
                or BaseMethodDeclarationSyntax
                or AccessorDeclarationSyntax) ?? node;

        bool addedAlias;
        do
        {
            addedAlias = false;
            foreach (VariableDeclaratorSyntax variable in searchRoot.DescendantNodes().OfType<VariableDeclaratorSyntax>())
            {
                if (variable.Initializer is null
                    || context.SemanticModel.GetDeclaredSymbol(variable, context.CancellationToken) is not ILocalSymbol { RefKind: not RefKind.None } local)
                {
                    continue;
                }

                ExpressionSyntax initializer = variable.Initializer.Value is RefExpressionSyntax refExpression
                    ? refExpression.Expression
                    : variable.Initializer.Value;
                ISymbol? initializedFrom = context.SemanticModel.GetSymbolInfo(UnwrapParentheses(initializer), context.CancellationToken).Symbol;
                if (initializedFrom is object
                    && (symbols.Contains(initializedFrom) || symbols.Contains(local))
                    && (symbols.Add(initializedFrom) | symbols.Add(local)))
                {
                    addedAlias = true;
                }
            }

            foreach (AssignmentExpressionSyntax assignment in searchRoot.DescendantNodes().OfType<AssignmentExpressionSyntax>())
            {
                if (assignment.Right is not RefExpressionSyntax refExpression
                    || context.SemanticModel.GetSymbolInfo(assignment.Left, context.CancellationToken).Symbol is not ILocalSymbol { RefKind: not RefKind.None } local)
                {
                    continue;
                }

                ISymbol? assignedFrom = context.SemanticModel.GetSymbolInfo(UnwrapParentheses(refExpression.Expression), context.CancellationToken).Symbol;
                if (assignedFrom is object
                    && (symbols.Contains(assignedFrom) || symbols.Contains(local))
                    && (symbols.Add(assignedFrom) | symbols.Add(local)))
                {
                    addedAlias = true;
                }
            }
        }
        while (addedAlias);

        return symbols.ToImmutable();
    }

    /// <summary>
    /// This is an explicit rule to ignore the code that was generated by Xaml2CS.
    /// </summary>
    /// <remarks>
    /// The generated code has the comments like this:
    /// <![CDATA[
    ///   //------------------------------------------------------------------------------
    ///   // <auto-generated>
    /// ]]>
    /// This rule is based on the fact the keyword "&lt;auto-generated&gt;" should be found in the comments.
    /// </remarks>
    internal static bool ShouldIgnoreContext(SyntaxNodeAnalysisContext context)
    {
        NamespaceDeclarationSyntax? namespaceDeclaration = context.Node.FirstAncestorOrSelf<NamespaceDeclarationSyntax>();
        if (namespaceDeclaration is object)
        {
            foreach (SyntaxTrivia trivia in namespaceDeclaration.NamespaceKeyword.GetAllTrivia())
            {
                const string autoGeneratedKeyword = @"<auto-generated>";
                if (trivia.FullSpan.Length > autoGeneratedKeyword.Length
                    && trivia.ToString().Contains(autoGeneratedKeyword))
                {
                    return true;
                }
            }
        }

        return false;
    }

    internal static void InspectMemberAccess(
        SyntaxNodeAnalysisContext context,
        MemberAccessExpressionSyntax? memberAccessSyntax,
        DiagnosticDescriptor descriptor,
        IEnumerable<CommonInterest.SyncBlockingMethod> problematicMethods,
        bool ignoreIfInsideAnonymousDelegate = false)
    {
        if (descriptor is null)
        {
            throw new ArgumentNullException(nameof(descriptor));
        }

        if (memberAccessSyntax is null)
        {
            return;
        }

        if (ShouldIgnoreContext(context))
        {
            return;
        }

        if (ignoreIfInsideAnonymousDelegate && context.Node.FirstAncestorOrSelf<AnonymousFunctionExpressionSyntax>() is object)
        {
            // We do not analyze JTF.Run inside anonymous functions because
            // they are so often used as callbacks where the signature is constrained.
            return;
        }

        if (CSharpUtils.IsWithinNameOf(context.Node as ExpressionSyntax))
        {
            // We do not consider arguments to nameof( ) because they do not represent invocations of code.
            return;
        }

        ITypeSymbol? typeReceiver = context.SemanticModel.GetTypeInfo(memberAccessSyntax.Expression).Type;
        if (typeReceiver is object)
        {
            foreach (CommonInterest.SyncBlockingMethod item in problematicMethods)
            {
                if (memberAccessSyntax.Name.Identifier.Text == item.Method.Name &&
                    typeReceiver.Name == item.Method.ContainingType.Name &&
                    typeReceiver.BelongsToNamespace(item.Method.ContainingType.Namespace))
                {
                    if (HasTaskCompleted(context, memberAccessSyntax))
                    {
                        return;
                    }

                    Location? location = memberAccessSyntax.Name.GetLocation();
                    context.ReportDiagnostic(Diagnostic.Create(descriptor, location));
                }
            }
        }
    }

    private static ExpressionSyntax UnwrapParentheses(ExpressionSyntax expression)
    {
        while (expression is ParenthesizedExpressionSyntax parenthesized)
        {
            expression = parenthesized.Expression;
        }

        return expression;
    }

    private static ExpressionSyntax GetTaskReceiver(MemberAccessExpressionSyntax memberAccessSyntax)
    {
        ExpressionSyntax receiver = UnwrapParentheses(memberAccessSyntax.Expression);
        if (receiver is InvocationExpressionSyntax getAwaiterInvocation
            && getAwaiterInvocation.Expression is MemberAccessExpressionSyntax { Name.Identifier.ValueText: "GetAwaiter" } getAwaiterAccess)
        {
            receiver = UnwrapParentheses(getAwaiterAccess.Expression);
        }

        if (receiver is InvocationExpressionSyntax configureAwaitInvocation
            && configureAwaitInvocation.Expression is MemberAccessExpressionSyntax { Name.Identifier.ValueText: nameof(Task.ConfigureAwait) } configureAwaitAccess)
        {
            receiver = UnwrapParentheses(configureAwaitAccess.Expression);
        }

        return receiver;
    }

    private static bool HasTaskCompleted(SyntaxNodeAnalysisContext context, MemberAccessExpressionSyntax memberAccessSyntax)
    {
        ExpressionSyntax taskReceiver = GetTaskReceiver(memberAccessSyntax);
        ITypeSymbol? taskType = context.SemanticModel.GetTypeInfo(taskReceiver, context.CancellationToken).Type;
        if (!Utils.IsTask(taskType)
            && !(taskType?.Name == nameof(ValueTask) && taskType.BelongsToNamespace(Namespaces.SystemThreadingTasks)))
        {
            return false;
        }

        ISymbol? taskSymbol = context.SemanticModel.GetSymbolInfo(taskReceiver, context.CancellationToken).Symbol;
        if (taskSymbol is not ILocalSymbol and not IParameterSymbol)
        {
            return false;
        }

        if (context.SemanticModel.GetEnclosingSymbol(memberAccessSyntax.SpanStart, context.CancellationToken) is not IMethodSymbol enclosingMethod
            || !SymbolEqualityComparer.Default.Equals(taskSymbol.ContainingSymbol, enclosingMethod))
        {
            return false;
        }

        ImmutableHashSet<ISymbol> taskSymbols = GetSymbolAndRefAliases(context, memberAccessSyntax, taskSymbol);
        if (NestedFunctionMayReassignTask(context, memberAccessSyntax, taskSymbols))
        {
            return false;
        }

        if (IsWithinCompletedTaskBranch(context, memberAccessSyntax, taskSymbols))
        {
            return true;
        }

        StatementSyntax? containingStatement = memberAccessSyntax.FirstAncestorOrSelf<StatementSyntax>();
        if (containingStatement is null)
        {
            return false;
        }

        if (TryGetAwaitExpression(context, containingStatement, taskSymbols, memberAccessSyntax.SpanStart, out AwaitExpressionSyntax? precedingAwait)
            && !MayReassignTask(context, containingStatement, taskSymbols, precedingAwait.Span.End, memberAccessSyntax.SpanStart))
        {
            return true;
        }

        while (containingStatement.Parent is BlockSyntax block)
        {
            if (MayReassignTask(context, containingStatement, taskSymbols, containingStatement.SpanStart - 1, memberAccessSyntax.SpanStart))
            {
                return false;
            }

            int statementIndex = block.Statements.IndexOf(containingStatement);
            for (int i = statementIndex - 1; i >= 0; i--)
            {
                StatementSyntax statement = block.Statements[i];
                if (StatementCompletesTask(context, statement, taskSymbols))
                {
                    return true;
                }

                if (MayReassignTask(context, statement, taskSymbols))
                {
                    return false;
                }
            }

            StatementSyntax? outerStatement = containingStatement.Ancestors().OfType<StatementSyntax>().FirstOrDefault(statement => statement.Parent is BlockSyntax);
            if (outerStatement is not IfStatementSyntax and not BlockSyntax)
            {
                return false;
            }

            if (MayReassignTask(context, outerStatement, taskSymbols, outerStatement.SpanStart - 1, containingStatement.SpanStart))
            {
                return false;
            }

            containingStatement = outerStatement;
        }

        return false;
    }

    private static bool IsWithinCompletedTaskBranch(
        SyntaxNodeAnalysisContext context,
        MemberAccessExpressionSyntax memberAccessSyntax,
        IImmutableSet<ISymbol> taskSymbols)
    {
        foreach (IfStatementSyntax ifStatement in memberAccessSyntax.Ancestors().OfType<IfStatementSyntax>())
        {
            IEnumerable<SyntaxNode> nodesBetweenAccessAndCondition = memberAccessSyntax.Ancestors().TakeWhile(node => node != ifStatement);
            if (nodesBetweenAccessAndCondition.Any(node => node is AnonymousFunctionExpressionSyntax or LocalFunctionStatementSyntax))
            {
                continue;
            }

            if (ifStatement.Statement.FullSpan.Contains(memberAccessSyntax.Span)
                && ConditionProvesCompletion(context, ifStatement.Condition, taskSymbols, conditionValue: true)
                && !MayReassignTask(context, ifStatement, taskSymbols, ifStatement.Condition.SpanStart - 1, memberAccessSyntax.SpanStart))
            {
                return true;
            }

            if (ifStatement.Else?.Statement.FullSpan.Contains(memberAccessSyntax.Span) is true
                && ConditionProvesCompletion(context, ifStatement.Condition, taskSymbols, conditionValue: false)
                && !MayReassignTask(context, ifStatement, taskSymbols, ifStatement.Condition.SpanStart - 1, memberAccessSyntax.SpanStart))
            {
                return true;
            }
        }

        return false;
    }

    private static bool ConditionProvesCompletion(
        SyntaxNodeAnalysisContext context,
        ExpressionSyntax condition,
        IImmutableSet<ISymbol> taskSymbols,
        bool conditionValue)
    {
        condition = UnwrapParentheses(condition);
        if (condition is PrefixUnaryExpressionSyntax { RawKind: (int)SyntaxKind.LogicalNotExpression } logicalNot)
        {
            return ConditionProvesCompletion(context, logicalNot.Operand, taskSymbols, !conditionValue);
        }

        if (condition is BinaryExpressionSyntax binary)
        {
            if (conditionValue && binary.IsKind(SyntaxKind.LogicalAndExpression))
            {
                return ConditionProvesCompletion(context, binary.Left, taskSymbols, conditionValue: true)
                    || ConditionProvesCompletion(context, binary.Right, taskSymbols, conditionValue: true);
            }

            if (!conditionValue && binary.IsKind(SyntaxKind.LogicalOrExpression))
            {
                return ConditionProvesCompletion(context, binary.Left, taskSymbols, conditionValue: false)
                    || ConditionProvesCompletion(context, binary.Right, taskSymbols, conditionValue: false);
            }

            if (conditionValue && binary.IsKind(SyntaxKind.LogicalOrExpression))
            {
                return ConditionProvesCompletion(context, binary.Left, taskSymbols, conditionValue: true)
                    && ConditionProvesCompletion(context, binary.Right, taskSymbols, conditionValue: true);
            }

            if (!conditionValue && binary.IsKind(SyntaxKind.LogicalAndExpression))
            {
                return ConditionProvesCompletion(context, binary.Left, taskSymbols, conditionValue: false)
                    && ConditionProvesCompletion(context, binary.Right, taskSymbols, conditionValue: false);
            }

            bool equalityHolds = binary.IsKind(SyntaxKind.EqualsExpression) ? conditionValue
                : binary.IsKind(SyntaxKind.NotEqualsExpression) ? !conditionValue
                : false;
            if ((binary.IsKind(SyntaxKind.EqualsExpression) || binary.IsKind(SyntaxKind.NotEqualsExpression))
                && IsRanToCompletionComparison(context, binary.Left, binary.Right, taskSymbols))
            {
                return equalityHolds;
            }
        }

        if (condition is MemberAccessExpressionSyntax completedProperty
            && IsOneOfSymbols(context, completedProperty.Expression, taskSymbols)
            && completedProperty.Name.Identifier.ValueText is nameof(Task.IsCompleted)
                or nameof(Task.IsCanceled)
                or nameof(Task.IsFaulted)
                or "IsCompletedSuccessfully")
        {
            return conditionValue;
        }

        return false;
    }

    private static bool IsRanToCompletionComparison(
        SyntaxNodeAnalysisContext context,
        ExpressionSyntax left,
        ExpressionSyntax right,
        IImmutableSet<ISymbol> taskSymbols)
    {
        return (IsTaskStatus(context, left, taskSymbols) && IsRanToCompletion(context, right))
            || (IsTaskStatus(context, right, taskSymbols) && IsRanToCompletion(context, left));
    }

    private static bool IsTaskStatus(SyntaxNodeAnalysisContext context, ExpressionSyntax expression, IImmutableSet<ISymbol> taskSymbols)
        => expression is MemberAccessExpressionSyntax { Name.Identifier.ValueText: nameof(Task.Status) } statusAccess
            && IsOneOfSymbols(context, statusAccess.Expression, taskSymbols);

    private static bool IsRanToCompletion(SyntaxNodeAnalysisContext context, ExpressionSyntax expression)
        => context.SemanticModel.GetSymbolInfo(expression, context.CancellationToken).Symbol is IFieldSymbol status
            && status.Name == nameof(TaskStatus.RanToCompletion)
            && status.ContainingType.Name == nameof(TaskStatus)
            && status.ContainingType.BelongsToNamespace(Namespaces.SystemThreadingTasks);

    private static bool StatementCompletesTask(
        SyntaxNodeAnalysisContext context,
        StatementSyntax statement,
        IImmutableSet<ISymbol> taskSymbols)
    {
        if (TryGetAwaitExpression(context, statement, taskSymbols, out AwaitExpressionSyntax? awaitExpression)
            && !MayReassignTask(context, statement, taskSymbols, awaitExpression.Span.End, statement.Span.End + 1))
        {
            return true;
        }

        if (statement is BlockSyntax block)
        {
            return StatementDefinitelyAwaitsTask(context, block, taskSymbols);
        }

        if (statement is not IfStatementSyntax ifStatement)
        {
            return false;
        }

        if (MayReassignTask(context, ifStatement.Condition, taskSymbols))
        {
            return false;
        }

        if (ifStatement.Else is null)
        {
            return ConditionProvesCompletion(context, ifStatement.Condition, taskSymbols, conditionValue: false)
                && StatementDefinitelyAwaitsTask(context, ifStatement.Statement, taskSymbols);
        }

        return (ConditionProvesCompletion(context, ifStatement.Condition, taskSymbols, conditionValue: true)
                && !MayReassignTask(context, ifStatement.Statement, taskSymbols)
                && StatementDefinitelyAwaitsTask(context, ifStatement.Else.Statement, taskSymbols))
            || (ConditionProvesCompletion(context, ifStatement.Condition, taskSymbols, conditionValue: false)
                && StatementDefinitelyAwaitsTask(context, ifStatement.Statement, taskSymbols)
                && !MayReassignTask(context, ifStatement.Else.Statement, taskSymbols));
    }

    private static bool StatementDefinitelyAwaitsTask(
        SyntaxNodeAnalysisContext context,
        StatementSyntax statement,
        IImmutableSet<ISymbol> taskSymbols)
    {
        if (TryGetAwaitExpression(context, statement, taskSymbols, out AwaitExpressionSyntax? awaitExpression))
        {
            return !MayReassignTask(context, statement, taskSymbols, awaitExpression.Span.End, statement.Span.End + 1);
        }

        if (statement is BlockSyntax block)
        {
            for (int i = block.Statements.Count - 1; i >= 0; i--)
            {
                if (TryGetAwaitExpression(context, block.Statements[i], taskSymbols, out awaitExpression)
                    && !MayReassignTask(context, block.Statements[i], taskSymbols, awaitExpression.Span.End, block.Statements[i].Span.End + 1))
                {
                    return true;
                }

                if (MayReassignTask(context, block.Statements[i], taskSymbols))
                {
                    return false;
                }
            }
        }

        return false;
    }

    private static bool TryGetAwaitExpression(
        SyntaxNodeAnalysisContext context,
        StatementSyntax statement,
        IImmutableSet<ISymbol> taskSymbols,
        [NotNullWhen(true)] out AwaitExpressionSyntax? awaitExpression)
        => TryGetAwaitExpression(context, statement, taskSymbols, statement.Span.End + 1, out awaitExpression);

    private static bool TryGetAwaitExpression(
        SyntaxNodeAnalysisContext context,
        StatementSyntax statement,
        IImmutableSet<ISymbol> taskSymbols,
        int beforePosition,
        [NotNullWhen(true)] out AwaitExpressionSyntax? awaitExpression)
    {
        static bool DescendIntoChildren(SyntaxNode node) => node is not AnonymousFunctionExpressionSyntax and not LocalFunctionStatementSyntax;

        if (statement is WhileStatementSyntax or DoStatementSyntax or ForStatementSyntax or ForEachStatementSyntax or ForEachVariableStatementSyntax)
        {
            awaitExpression = null;
            return false;
        }

        foreach (AwaitExpressionSyntax candidate in statement.DescendantNodes(DescendIntoChildren).OfType<AwaitExpressionSyntax>().Reverse())
        {
            if (candidate.Span.End >= beforePosition)
            {
                continue;
            }

            IEnumerable<SyntaxNode> ancestorsWithinStatement = candidate.Ancestors().TakeWhile(node => node != statement);
            bool isConditionallyExecuted = ancestorsWithinStatement.Any(
                node => node is StatementSyntax
                    or ConditionalExpressionSyntax
                    or SwitchExpressionSyntax
                    or ConditionalAccessExpressionSyntax
                    or WhenClauseSyntax
                    || (node is BinaryExpressionSyntax binary
                        && (binary.IsKind(SyntaxKind.LogicalAndExpression)
                            || binary.IsKind(SyntaxKind.LogicalOrExpression)
                            || binary.IsKind(SyntaxKind.CoalesceExpression))
                        && binary.Right.FullSpan.Contains(candidate.Span)));
            if (!isConditionallyExecuted && AwaitCompletesTask(context, candidate, taskSymbols))
            {
                awaitExpression = candidate;
                return true;
            }
        }

        awaitExpression = null;
        return false;
    }

    private static bool AwaitCompletesTask(
        SyntaxNodeAnalysisContext context,
        AwaitExpressionSyntax awaitExpression,
        IImmutableSet<ISymbol> taskSymbols)
    {
        if (MayReassignTask(context, awaitExpression.Expression, taskSymbols))
        {
            return false;
        }

        ExpressionSyntax awaitedExpression = UnwrapParentheses(awaitExpression.Expression);
        if (awaitedExpression is InvocationExpressionSyntax configureAwaitInvocation
            && configureAwaitInvocation.Expression is MemberAccessExpressionSyntax { Name.Identifier.ValueText: nameof(Task.ConfigureAwait) } configureAwaitAccess)
        {
            awaitedExpression = UnwrapParentheses(configureAwaitAccess.Expression);
        }

        if (IsOneOfSymbols(context, awaitedExpression, taskSymbols))
        {
            return true;
        }

        if (awaitedExpression is InvocationExpressionSyntax whenAllInvocation
            && context.SemanticModel.GetSymbolInfo(whenAllInvocation, context.CancellationToken).Symbol is IMethodSymbol whenAllMethod
            && whenAllMethod.Name == nameof(Task.WhenAll)
            && whenAllMethod.ContainingType.Name == nameof(Task)
            && whenAllMethod.ContainingType.BelongsToNamespace(Namespaces.SystemThreadingTasks))
        {
            return whenAllInvocation.ArgumentList.Arguments.Any(argument => IsOneOfSymbols(context, argument.Expression, taskSymbols));
        }

        return false;
    }

    private static bool MayReassignTask(SyntaxNodeAnalysisContext context, SyntaxNode node, IImmutableSet<ISymbol> taskSymbols)
        => MayReassignTask(context, node, taskSymbols, node.SpanStart - 1, node.Span.End + 1);

    private static bool MayReassignTask(
        SyntaxNodeAnalysisContext context,
        SyntaxNode node,
        IImmutableSet<ISymbol> taskSymbols,
        int afterPosition,
        int beforePosition)
    {
        bool DescendIntoChildren(SyntaxNode child) =>
            child == node || child is not AnonymousFunctionExpressionSyntax and not LocalFunctionStatementSyntax;

        foreach (AssignmentExpressionSyntax assignment in node.DescendantNodesAndSelf(DescendIntoChildren).OfType<AssignmentExpressionSyntax>())
        {
            if (assignment.SpanStart > afterPosition
                && assignment.SpanStart < beforePosition
                && IsAssignmentToTask(context, assignment.Left, taskSymbols))
            {
                return true;
            }
        }

        foreach (ArgumentSyntax argument in node.DescendantNodesAndSelf(DescendIntoChildren).OfType<ArgumentSyntax>())
        {
            if (argument.SpanStart > afterPosition
                && argument.SpanStart < beforePosition
                && (argument.RefKindKeyword.IsKind(SyntaxKind.RefKeyword) || argument.RefKindKeyword.IsKind(SyntaxKind.OutKeyword))
                && IsOneOfSymbols(context, argument.Expression, taskSymbols))
            {
                return true;
            }
        }

        return false;
    }

    private static bool NestedFunctionMayReassignTask(
        SyntaxNodeAnalysisContext context,
        SyntaxNode node,
        IImmutableSet<ISymbol> taskSymbols)
    {
        SyntaxNode? containingFunction = node.Ancestors().FirstOrDefault(
            ancestor => ancestor is AnonymousFunctionExpressionSyntax or LocalFunctionStatementSyntax or BaseMethodDeclarationSyntax);
        return containingFunction?.DescendantNodes()
            .Where(descendant => descendant is AnonymousFunctionExpressionSyntax or LocalFunctionStatementSyntax)
            .Any(nestedFunction => MayReassignTask(context, nestedFunction, taskSymbols)) is true;
    }

    private static bool IsAssignmentToTask(SyntaxNodeAnalysisContext context, ExpressionSyntax expression, IImmutableSet<ISymbol> taskSymbols)
    {
        expression = UnwrapParentheses(expression);
        if (expression is TupleExpressionSyntax tuple)
        {
            return tuple.Arguments.Any(argument => IsAssignmentToTask(context, argument.Expression, taskSymbols));
        }

        return IsOneOfSymbols(context, expression, taskSymbols);
    }

    private static bool IsOneOfSymbols(SyntaxNodeAnalysisContext context, ExpressionSyntax expression, IImmutableSet<ISymbol> symbols)
    {
        ISymbol? symbol = context.SemanticModel.GetSymbolInfo(UnwrapParentheses(expression), context.CancellationToken).Symbol;
        return symbol is object && symbols.Contains(symbol);
    }
}
