steps:

- task: ms-vseng.MicroBuildTasks.965C8DC6-1483-45C9-B384-5AC75DA1F1A4.MicroBuildOptProfPlugin@4
  inputs:
    optimizationInputsDropNamePrefix: OptimizationData/DevDiv/vs-threading
    version: 1.1.85-ge381a1be51
    feedSource: https://devdiv-test.pkgs.visualstudio.com/DefaultCollection/_packaging/MicroBuildToolset/nuget/v3/index.json
  displayName: Install OptProf Plugin

- task: MicroBuildSigningPlugin@1
  inputs:
    signType: $(SignType)
    zipSources: false
  displayName: Install MicroBuild Signing Plugin
  condition: and(succeeded(), ne(variables['Hosted'], 'true'))
