trigger: none # We only want to trigger manually or based on resources
pr: none

resources:
  repositories:
  - repository: MicroBuildTemplate
    type: git
    name: 1ESPipelineTemplates/MicroBuildTemplate
    ref: refs/tags/release
  pipelines:
  - pipeline: CI
    source: vs-threading
    trigger:
      tags:
      - auto-release

variables:
- template: GlobalVariables.yml

extends:
  template: azure-pipelines/MicroBuild.1ES.Official.yml@MicroBuildTemplate
  parameters:
    sdl:
      sourceAnalysisPool: VSEngSS-MicroBuild2022-1ES

    stages:
    - stage: release
      jobs:
      - job: release
        pool:
          name: AzurePipelines-EO
          demands:
          - ImageOverride -equals 1ESPT-Ubuntu22.04
          os: Linux
        steps:
        - checkout: none
        - powershell: |
            Write-Host "##vso[build.updatebuildnumber]$(resources.pipeline.CI.runName)"
            if ('$(resources.pipeline.CI.runName)'.Contains('-')) {
              Write-Host "##vso[task.setvariable variable=IsPrerelease]true"
            } else {
              Write-Host "##vso[task.setvariable variable=IsPrerelease]false"
            }
          displayName: ⚙ Set up pipeline
