steps:

- task: UseDotNet@2
  displayName: Install .NET Core SDK 2.2.401
  inputs:
    packageType: sdk
    version: 2.2.401

- task: UseDotNet@2
  displayName: Install .NET Core 2.1 runtime
  inputs:
    packageType: runtime
    version: 2.1.x

- script: dotnet --info
  displayName: Show dotnet SDK info

- script: dotnet restore
  displayName: Restore packages
  workingDirectory: ${{ parameters.projectdirectory }}

- script: dotnet build --no-restore -v n -c $(BuildConfiguration) /bl:"$(Build.ArtifactStagingDirectory)/build_logs/build.binlog"
  displayName: Build test
  workingDirectory: ${{ parameters.projectdirectory }}

- script: dotnet test -v n -f netcoreapp2.1 -c $(BuildConfiguration) --no-build --filter "TestCategory!=FailsInCloudTest"
  displayName: Run tests for netcoreapp2.1 on the .NET Core 2.1 runtime
  workingDirectory: ${{ parameters.projectdirectory }}
  env:
    DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX: 0
    RuntimeFrameworkVersion: 2.1
  enabled: false # TODO: figure out why this step hangs

- script: dotnet test -v n -f netcoreapp2.1 -c $(BuildConfiguration) --no-build --filter "TestCategory!=FailsInCloudTest"
  displayName: Run tests for netcoreapp2.1 on the .NET Core 2.2 runtime
  workingDirectory: ${{ parameters.projectdirectory }}
  env:
    DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX: 0
    RuntimeFrameworkVersion: 2.2
  enabled: false # TODO: figure out why this step hangs
